services:
  - type: web
    name: expense-tracker-web
    env: python
    buildCommand: |
      pip install poetry
      poetry install
      mkdir -p static/css static/js
    startCommand: poetry run python run_web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 8000
    plan: free
    autoDeploy: true
    healthCheckPath: /
    domains:
      - expense-tracker.onrender.com

  - type: worker
    name: expense-tracker-bot
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run python run_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: WEBHOOK_URL
        value: https://expense-tracker.onrender.com/webhook
    plan: free 