services:
  - type: worker
    name: expense-tracker-bot
    env: python
    buildCommand: pip install poetry && poetry install
    startCommand: poetry run python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false 